### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by hrolf** [gnomeontherun/ionic-definitive-guide#1]
In your demo refresh does not work for newly added symbols! Add a new symbol, thats ok but when you do a refresh the new symbol will disapear. In my app it only worked when the app was reloaded so the symbol was actually saved but was not showed unless you restarted the app. Why? And can it be fixad?
Regards Rolf

**Comment by gnomeontherun** [comment]
Hi Rolf,

So to be clear, when you add a symbol on the Quotes tab, it appears, but when you pull down to refresh, it disappears?

I can't seem to reproduce this error on the demo here: https://ionic-starter-guide.herokuapp.com/#/tabs/quotes which is using the exact code in this repository. Did you copy the code directly from this repo to run, or follow along and copy code into it from the article?

**Comment by hrolf** [comment]
HI Jeremy,
Thats right plus that reorder does not work either. I tested with the
demolink in the mail with the same result on the phone and on the PC. The
funny thing is that all worked if you reload the demo. Then the new symbol
is there and the reorder is right so it seems that the display is not
updated correctly in the first place. I am using Sony mobile with android
and PC with Chrom and Firefox.
Regards Rolf

2015-07-06 2:20 GMT+02:00 Jeremy Wilken notifications@github.com:

**Comment by gnomeontherun** [comment]
Found it. The symbol wasn't being correctly stored in the `symbols` array, which is used to by the loading method. So on reload, it was dropping the new symbol. Thanks for the catch, I'll update the post on airpair as well.

``` javascript
$scope.add = function() {
    if ($scope.form.query) {
      QuotesService.get([$scope.form.query]).then(function(results) {
        if (results[0].Name) {
          symbols.push($scope.form.query); // Added this line
          $scope.quotes.push(results[0]);
          $scope.form.query = '';
          updateSymbols();
        } else {
          $ionicPopup.alert({
            title: 'Could not locate symbol.'
          });
        }
      });
    }
  };
```

**Comment by hrolf** [comment]
Hi Jeremy,
That worked but only partly. Reorder and Remove have the same problem. For
me it seems to be a problem with the browser which is not completed
updated. When you reload the browser it works!!

But I am not an expert. I am 71 years old with none or little experience of
programming but I find it interesting to develop apps with help of ionics.
What I find difficult is testing. I would appreciate if you could write an
article about testing for beginners. Today I only use ionec serve but that
make it difficult when nothing is working.
Regards Rolf

2015-07-07 2:43 GMT+02:00 Jeremy Wilken notifications@github.com:

**Comment by gnomeontherun** [comment]
I pushed up some additional changes, the same problem affected reordering. It should now keep the newly added things even if you don't do a hard refresh.

Testing is a difficult thing, and I have a whole chapter on it in my book. However, you might find this post to be useful for writing automated tests with Angular (which applies the same for Ionic) https://www.airpair.com/angularjs/posts/unit-testing-angularjs-applications.

**Comment by hrolf** [comment]
Hi,
I see what you changed but why did it not worked the first time?
/Rolf

lördag 11 juli 2015 skrev Jeremy Wilken notifications@github.com:

**Comment by gnomeontherun** [comment]
Hi Rolf,

The list of symbols used to load quotes was loaded once, and changes to the list (which is stored in the `quotes` array) were lost anytime you made changes to the list of quotes. The `symbols` array wasn't being updated each time, and they were out of sync, causing the issue you pointed out. Thanks!

Jeremy
